/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageSourcesRouteImport } from './routes/manage-sources'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TvShowsRouteImport } from './routes/tv-shows'
import { Route as TitleMediaTypeTmdbIdRouteImport } from './routes/title.$mediaType.$tmdbId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSourcesRoute = ManageSourcesRouteImport.update({
  id: '/manage-sources',
  path: '/manage-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TvShowsRoute = TvShowsRouteImport.update({
  id: '/tv-shows',
  path: '/tv-shows',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleMediaTypeTmdbIdRoute = TitleMediaTypeTmdbIdRouteImport.update({
  id: '/title/$mediaType/$tmdbId',
  path: '/title/$mediaType/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage-sources': typeof ManageSourcesRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/tv-shows': typeof TvShowsRoute
  '/title/$mediaType/$tmdbId': typeof TitleMediaTypeTmdbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage-sources': typeof ManageSourcesRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/tv-shows': typeof TvShowsRoute
  '/title/$mediaType/$tmdbId': typeof TitleMediaTypeTmdbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage-sources': typeof ManageSourcesRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/tv-shows': typeof TvShowsRoute
  '/title/$mediaType/$tmdbId': typeof TitleMediaTypeTmdbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage-sources'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/tv-shows'
    | '/title/$mediaType/$tmdbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manage-sources'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/tv-shows'
    | '/title/$mediaType/$tmdbId'
  id:
    | '__root__'
    | '/'
    | '/manage-sources'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/tv-shows'
    | '/title/$mediaType/$tmdbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageSourcesRoute: typeof ManageSourcesRoute
  MoviesRoute: typeof MoviesRoute
  MyListRoute: typeof MyListRoute
  SearchRoute: typeof SearchRoute
  TvShowsRoute: typeof TvShowsRoute
  TitleMediaTypeTmdbIdRoute: typeof TitleMediaTypeTmdbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-sources': {
      id: '/manage-sources'
      path: '/manage-sources'
      fullPath: '/manage-sources'
      preLoaderRoute: typeof ManageSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-shows': {
      id: '/tv-shows'
      path: '/tv-shows'
      fullPath: '/tv-shows'
      preLoaderRoute: typeof TvShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$mediaType/$tmdbId': {
      id: '/title/$mediaType/$tmdbId'
      path: '/title/$mediaType/$tmdbId'
      fullPath: '/title/$mediaType/$tmdbId'
      preLoaderRoute: typeof TitleMediaTypeTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageSourcesRoute: ManageSourcesRoute,
  MoviesRoute: MoviesRoute,
  MyListRoute: MyListRoute,
  SearchRoute: SearchRoute,
  TvShowsRoute: TvShowsRoute,
  TitleMediaTypeTmdbIdRoute: TitleMediaTypeTmdbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
